name: 步步宝mama

on:
    workflow_dispatch:
    schedule:
        - cron: "45 5-20 * * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
            - name: "运行【步步宝mama】"
              run: |
                  node bbb.js
              env:
                  BBBCK: ${{ secrets.BBBCK5 }}
