name: 葱花视频

on:
  workflow_dispatch:

  schedule:
     - cron: '*/30 * * * *'
  watch:
    types: started
jobs:
  build:
    env:
      TASKCENTERBODY: ${{ secrets.TASKCENTERBODY }}
      SHAREBODY: ${{ secrets.SHAREBODY }}
      SHAREREWARDBODY: ${{ secrets.SHAREREWARDBODY }}
      TIMEREDBODY: ${{ secrets.TIMEREDBODY }}
      READBODY: ${{ secrets.READBODY}}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【葱花视频-时段奖励】'
        if: env.TASKCENTERBODY      
        run: |
          node Task/chonghua1.js
        env:
          TASKCENTERBODY: ${{ secrets.TASKCENTERBODY }}
          TIMEREDBODY: ${{ secrets.TIMEREDBODY }}
      - name: '运行 【葱花视频-分享奖励】'
        if: env.SHAREBODY      
        run: |
          node Task/chonghua2.js 
        env:
          TASKCENTERBODY: ${{ secrets.TASKCENTERBODY }}
          SHAREBODY: ${{ secrets.SHAREBODY }}
          SHAREREWARDBODY: ${{ secrets.SHAREREWARDBODY }}              
    
